name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=2G
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: create test database
        run: php bin/console doctrine:schema:create --env=test

      - name: Run tests
        run: vendor/bin/phpunit

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=2G
          coverage: none

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Set up environment
        run: cp .env.prod .env

      - name: Build assets
        run: php bin/console assets:install

      - name: Clear and warm up cache
        run: |
          php bin/console cache:clear --env=prod
          php bin/console cache:warmup --env=prod

      - name: Publish
        uses: nogsantos/scp-deploy@v1.3.0
        with:
          src: ./public/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
